"""Read and validate NeuroQP project exports."""

from ._api import (
    Animal,
    Classification,
    ClassificationModule,
    ClassificationResult,
    ClassificationResults,
    FileArtifact,
    Image,
    Match,
    MatchResult,
    MatchResults,
    ProjectExport,
    Registration,
    Slice,
    SliceRegistration,
    Staining,
)
from ._reader import open_export, validate_export
from .errors import (
    AmbiguousNameError,
    ClosedExportError,
    InvalidExportError,
    NeuroQPError,
    ObjectNotFoundError,
    UnsupportedVersionError,
)
from .models import (
    Atlas,
    AtlasRegistration,
    BrainRegion,
    ClassificationResultInfo,
    ClassifierMetadata,
    DetailTransform,
    ExportLimits,
    ExportMetadata,
    IndependentDetectionSource,
    Manifest,
    MatchResultInfo,
    ProjectMetadata,
    SharedDetectionSource,
    SliceExclusion,
    TrainingSample,
    TrainingSummary,
    ValidationIssue,
    ValidationReport,
)

__version__ = "0.1.0"

__all__ = [
    "AmbiguousNameError",
    "Animal",
    "Atlas",
    "AtlasRegistration",
    "BrainRegion",
    "Classification",
    "ClassificationModule",
    "ClassificationResult",
    "ClassificationResultInfo",
    "ClassificationResults",
    "ClassifierMetadata",
    "ClosedExportError",
    "DetailTransform",
    "ExportLimits",
    "ExportMetadata",
    "FileArtifact",
    "Image",
    "IndependentDetectionSource",
    "InvalidExportError",
    "Manifest",
    "Match",
    "MatchResult",
    "MatchResultInfo",
    "MatchResults",
    "NeuroQPError",
    "ObjectNotFoundError",
    "ProjectExport",
    "ProjectMetadata",
    "Registration",
    "SharedDetectionSource",
    "Slice",
    "SliceExclusion",
    "SliceRegistration",
    "Staining",
    "TrainingSample",
    "TrainingSummary",
    "UnsupportedVersionError",
    "ValidationIssue",
    "ValidationReport",
    "__version__",
    "open_export",
    "validate_export",
]
